#server:
#    port: 8080
##文件上传配置
#multipart:
#    enabled: true
#    maxFileSize: 100Mb
#    maxRequestSize: 100Mb
##    location: ./upload
#
## MyBatis
#mybatis:
#    mapper-locations: classpath:mappers/**/*.xml
#    config: classpath:config/mybatis-config.xml
##    dynamic-datasource: true  #启用mybatis动态数据源
#
#
#hsweb:
#    dynamic-datasource: #动态数据源配置
#          url: jdbc:mysql://localhost:3306/hsweb??useUnicode=true&characterEncoding=utf-8
#          username: root
#          password: 123456
#          icatch:
#            max-actives: 100
#            output-dir: ./data/atomikos
#            log_base_dir: ./data/atomikos
#            default-jta-timeout: 300000
#          type: mysql
#    access-logger: on #开启访问日志
#
#spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/hsweb??useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: 123456
#      type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource